pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS = credentials('mle-template')
        DB_CREDS        = credentials('pgaas-lab2')
        VAULT_CREDS     = credentials('vault_lab_3')
        PROJECT_NAME    = "BigDataLab4"
        IMAGE_NAME      = "lab4"
        PG_DB           = "postgres"
        LANGUAGE    = "C.UTF-8"
        LANG        = "C.UTF-8"
        LC_COLLATE  = "C.UTF-8"
        LC_CTYPE    = "C.UTF-8"
        LC_MONETARY = "C.UTF-8"
        LC_NUMERIC  = "C.UTF-8"
        LC_TIME     = "C.UTF-8"
        LC_MESSAGES = "C.UTF-8"
        LC_ALL      = "C.UTF-8"
    }

options {
        timestamps()
        skipDefaultCheckout(true)
	}
    stages {
        stage('Clone github repository') {
            steps {
                cleanWs()
                sh 'git clone -b main https://github.com/Timoniche/$PROJECT_NAME.git'
			}
		}

        stage('Checkout repo dir') {
            steps {
                sh 'cd $PROJECT_NAME && dir'
			}
	    }

        stage('Login') {
            steps {
                sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW'
            }
        }

        stage('Building docker') {
            steps {
                sh 'cd $PROJECT_NAME && docker compose build'
            }
        }

        stage('Installing ansible') { //TODO: move to jenkins docker build someday
            steps {
                sh 'apt-get install -y ansible'
            }
        }

        stage('Decrypting .env file from vault') {
            steps {
                dir("$PROJECT_NAME") {
                    sh 'echo $VAULT_CREDS_PSW > vault_pwd.txt'
                    sh 'ansible-vault decrypt vault_env.yml --vault-password-file vault_pwd.txt -v'
                    sh 'cp vault_env.yml .env'
                }
            }
        }

        stage('Create and run docker container') {
            steps {
                dir("$PROJECT_NAME") {
                    sh 'docker compose up -d'
                }
            }
        }

        stage('Clearing sensitive files') {
            steps {
                dir("$PROJECT_NAME") {
                    sh 'ansible-vault encrypt vault_env.yml --vault-password-file vault_pwd.txt'
                    sh 'cat vault_env.yml'
                    sh 'rm -f vault_pwd.txt'
                    sh 'rm -f .env'
                }
            }
        }

        stage('Checkout coverage report, images') {
            steps{
                dir("$PROJECT_NAME") {
                    sh 'docker compose images'
                    sh 'docker compose logs -t --tail 50'
                }
            }
        }

        stage('Push') {
            steps {
                sh 'docker push ddulaev/$IMAGE_NAME:latest'
            }
        }
	}

    post {
        always {
            dir("$PROJECT_NAME") {
                sh 'docker compose down'
                sh 'docker logout'
                sh 'rm -f vault_pwd.txt'
                sh 'rm -f .env'
            }
        }
    }
}
